# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "master" branch
  push:
    branches: [ "master", "test-ci" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "deploy to ec2"
        uses: "easingthemes/ssh-deploy@main"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          ARGS: "-rvP --delete"
          SOURCE: "docs/*"
          REMOTE_HOST: bar.my-tai.net
          REMOTE_USER: ubuntu
          TARGET: /opt/nginx/html/
